branch-defaults:
  default:
    environment: RouteFinder-REST-API-env
environment-defaults:
  your-env-name:
    platform: python-3.12
    tier: WebServer
global:
  application_name: RouteFinder-REST-API
  default_region: us-east-1
  workspace_type: Application
