# Generated by Django 5.2.7 on 2025-11-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Search",
            fields=[
                ("search_id", models.TextField(primary_key=True, serialize=False)),
                ("search_datetime", models.DateTimeField()),
            ],
        ),
    ]
