# Generated by Django 5.2.7 on 2025-11-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searches", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="search",
            name="id",
        ),
        migrations.AlterField(
            model_name="search",
            name="search_id",
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
