# Generated by Django 5.2.7 on 2025-11-09 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("searches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trip_id", models.TextField(default="noid")),
                ("departure_id", models.CharField(max_length=3)),
                ("departure_airport", models.TextField(null=True)),
                ("departure_time", models.CharField(max_length=8, null=True)),
                ("arrival_id", models.CharField(max_length=3, null=True)),
                ("arrival_airport", models.TextField(null=True)),
                ("arrival_time", models.CharField(max_length=8, null=True)),
                ("type", models.CharField(max_length=20, null=True)),
                ("price", models.IntegerField(default=0)),
                ("duration", models.IntegerField(default=0)),
                ("outbound_date", models.CharField(max_length=10, null=True)),
                ("arrival_date", models.CharField(max_length=10, null=True)),
                ("travel_class", models.CharField(max_length=20, null=True)),
                ("airline_logo", models.TextField(null=True)),
                ("airline_name", models.TextField(null=True)),
                (
                    "search_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="searches.search",
                    ),
                ),
            ],
        ),
    ]
