# Generated by Django 5.2.7 on 2025-10-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engine", models.CharField(default="google_flights", max_length=14)),
                ("api_key", models.TextField(verbose_name="placeholder")),
                ("departure_id", models.CharField(max_length=3)),
                ("arrival_id", models.CharField(max_length=3)),
                ("gl", models.CharField(max_length=2)),
                ("hl", models.CharField(max_length=2)),
                ("type", models.IntegerField(default=1)),
                ("outbound_date", models.DateTimeField()),
                ("return_date", models.DateTimeField()),
                ("travel_class", models.IntegerField(blank=True, null=True)),
                ("exclude_basic", models.BooleanField(default=False)),
                ("deep_search", models.BooleanField(default=False)),
            ],
        ),
    ]
