# Generated by Django 5.2.7 on 2025-11-06 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("searches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "flight_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("trip_id", models.TextField(default="noid")),
                ("departure_id", models.CharField(max_length=3)),
                ("arrival_id", models.CharField(max_length=3)),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField()),
                ("type", models.CharField(max_length=20)),
                ("price", models.IntegerField(default=0)),
                ("duration", models.IntegerField(default=0)),
                ("outbound_date", models.DateTimeField()),
                ("travel_class", models.CharField(max_length=20, null=True)),
                (
                    "search_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="searches.search",
                    ),
                ),
            ],
        ),
    ]
