# Generated by Django 5.2.7 on 2025-11-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="arrival_airport",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="flight",
            name="departure_airport",
            field=models.TextField(null=True),
        ),
    ]
