# Generated by Django 5.2.7 on 2025-10-30 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="api_key",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="deep_search",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="engine",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="exclude_basic",
        ),
    ]
