# Generated by Django 5.2.7 on 2025-11-13 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
        ('searches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='search_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searches.search'),
        ),
    ]
