# Generated by Django 5.2.7 on 2025-11-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_arrival_airport_flight_departure_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airline_logo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='airline_name',
            field=models.TextField(null=True),
        ),
    ]
