# Generated by Django 5.2.7 on 2025-11-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0002_remove_flight_api_key_remove_flight_deep_search_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="search_id",
            field=models.TextField(default=0),
        ),
    ]
