# Generated by Django 5.2.7 on 2025-11-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flight_search_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
