# Generated by Django 5.2.7 on 2025-11-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0003_flight_search_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="search_id",
            field=models.TextField(default="noid"),
        ),
    ]
