# Generated by Django 5.2.7 on 2025-11-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_flight_duration_alter_flight_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
