# Generated by Django 5.2.7 on 2025-11-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0004_alter_flight_search_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="gl",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="hl",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="return_date",
        ),
        migrations.AlterField(
            model_name="flight",
            name="travel_class",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="flight",
            name="type",
            field=models.CharField(max_length=20),
        ),
    ]
