# Generated by Django 5.2.7 on 2025-11-06 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0005_remove_flight_gl_remove_flight_hl_and_more"),
        ("searches", "0002_remove_search_id_alter_search_search_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="id",
        ),
        migrations.AddField(
            model_name="flight",
            name="duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="flight",
            name="flight_id",
            field=models.CharField(
                default="noid", max_length=10, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flight",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="flight",
            name="trip_id",
            field=models.TextField(default="noid"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="search_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="searches.search"
            ),
        ),
    ]
